### ISSUE TITLE
function misnamed in VertexArrayObject.h

### ISSUE THREAD

**Issue by fannart** [NCCA/NGL#10]
Just wondering if this shouldn't be VAO insted of VOA.

//----------------------------------------------------------------------------------------------------------------------
    /// @brief method to return a newVOA object
    /// @returns a new VOA object
    //----------------------------------------------------------------------------------------------------------------------
    static VertexArrayObject \* createVOA(   GLenum _mode    )
    {
        return new VertexArrayObject(_mode);
    }

**Comment by jmacey** [comment]
yes i guess it should but would mean re-writing loads of demos so will leave it for this year!

**Comment by fannart** [comment]
Might want to look at 
```c++
void VertexArrayObject::removeVOA()
```
while you're at it :)

**Comment by jmacey** [comment]
Fixed in master, and new Factories
