### ISSUE TITLE
Curiosity: Vec4 m_w defaults to 0.0f

### ISSUE THREAD

**Issue by j0yu** [NCCA/NGL#5]
Just wondering about the `m_w = 0.0f;` 
Shouldn't it be `1` instead? 

I was stumped when multiplying **Vec4** and **Mat4** together to find that translate did not work as I assumed Vec4 homogeneous coordinate will be 1. 
![image](https://cloud.githubusercontent.com/assets/9294702/6040652/111af364-ac6c-11e4-8a1e-fc2490ec379a.png)

**Comment by jmacey** [comment]
yes by default it’s a vector if you want to use it as a point you have to explicitly set it to 1.0

helps in teaching and is really cruel

Jon
On 4 Feb 2015, at 12:55, j0yu <notifications@github.com<mailto:notifications@github.com>> wrote:


Just wondering about the m_w = 0.0f;
Shouldn't it be 1 instead?

I was stumped when multiplying Vec4 and Mat4 together to find that translate did not work as I assumed Vec4 will be homogeneous.
[image]<https://cloud.githubusercontent.com/assets/9294702/6040652/111af364-ac6c-11e4-8a1e-fc2490ec379a.png>

—
Reply to this email directly or view it on GitHub<https://github.com/NCCA/NGL/issues/5>.

BU is a Disability Two Ticks Employer and has signed up to the Mindful Employer charter. Information about the accessibility of University buildings can be found on the BU DisabledGo webpages This email is intended only for the person to whom it is addressed and may contain confidential information. If you have received this email in error, please notify the sender and delete this email, which must not be copied, distributed or disclosed to any other person. Any views or opinions presented are solely those of the author and do not necessarily represent those of Bournemouth University or its subsidiary companies. Nor can any contract be formed on behalf of the University or its subsidiary companies via email.
